version: '3.4'

services:
  efecty:
    image: efecty
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - cocky_diffie
    networks: 
      - my_net
  cocky_diffie:
    image: redis:3.2.0
    networks: 
      - my_net
networks: 
  my_net:
    driver: bridge